packages:
  - packages/*

catalogs:
  ui:
    "@janis.me/themed": "0.2.2"
    "include-media": "^2.0.0"
    "sanitize.css": "^13.0.0"
  build:
    "@astrojs/rss": "^4.0.13"
    "@astrojs/sitemap": "^3.6.0"
    "astro-pdf": "^1.7.2"
    "@brandonaaron/astro-script-embed": "^1.0.3"
    "@shikijs/transformers": "^3.15.0"
    "astro-webmanifest": "^1.0.0"
    "astro": "^5.15.9"
    "sanitize-html": "^2.17.0"
    "sharp": "^0.34.5"
    cssnano: ^7.1.2
    postcss: ^8.5.6
    sass: ^1.94.1
    typescript: ^5.9.3
    vite-plugin-static-copy: ^3.1.4
    vite: ^7.2.2
  fonts:
    "@fontsource/ibm-plex-mono": "^5.2.7"
    "@fortawesome/fontawesome-svg-core": "^7.1.0"
    "@fortawesome/free-brands-svg-icons": "^7.1.0"
    "@fortawesome/free-solid-svg-icons": "^7.1.0"
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.7.0
    prettier: ^3.6.2
    prettier-plugin-packagejson: ^2.5.19
  lint:
    "@eslint/eslintrc": ^3.3.1
    "@eslint/js": ^9.39.1
    eslint: ^9.39.1
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^7.0.1
    jiti: ^2.6.1
    typescript-eslint: ^8.47.0
  script:
    taze: ^19.9.0
  types:
    "@types/node": ^22.19.1
    "@types/sanitize-html": ^2.16.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - puppeteer
  - sharp
  - workerd

overrides:
  rollup: npm:@rollup/wasm-node

supportedArchitectures:
  os: [ linux ]
