packages:
  - packages/*

catalogs:
  build:
    cssnano: ^7.1.1
    postcss: ^8.5.6
    sass: ^1.90.0
    typescript: ^5.9.2
    vite: ^6.3.5
    vite-plugin-static-copy: ^2.3.2
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.6.2
    prettier: ^3.6.2
    prettier-plugin-packagejson: ^2.5.19
  lint:
    "@eslint/eslintrc": ^3.3.1
    "@eslint/js": ^9.34.0
    eslint: ^9.34.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    jiti: ^2.5.1
    typescript-eslint: ^8.40.0
  script:
    taze: ^19.3.0
  types:
    "@types/node": ^22.18.0
    "@types/sanitize-html": ^2.16.0

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - puppeteer
  - sharp
  - workerd

overrides:
  rollup: npm:@rollup/wasm-node
  puppeteer: "@cloudflare/puppeteer"

supportedArchitectures:
  os: [wasm, linux]
